extend = [
    { path = "makefiles/Pi.toml" },
    { path = "makefiles/Github.toml" },
    { path = "makefiles/Helm.toml" },
    { path = "makefiles/S3.toml" },
    { path = "examples/robot-assistant.toml" },
]

[config]
default_to_workspace = false

[tasks.build]
args = ["build"]
