/// WARNING: CODE GENERATED FILE
/// * This file is generated by kfspec2code.
/// * Any changes applied to this file will be lost when a new spec is generated.
use serde::{Deserialize, Serialize};

use kf_protocol_api::ErrorCode;
use kf_protocol_api::Request;

use kf_protocol_derive::Decode;
use kf_protocol_derive::Encode;
use kf_protocol_derive::KfDefault;

// -----------------------------------
// KfDeleteGroupsRequest
// -----------------------------------

#[derive(Encode, Decode, Serialize, Deserialize, KfDefault, Debug)]
pub struct KfDeleteGroupsRequest {
    /// The group names to delete.
    pub groups_names: Vec<String>,
}

// -----------------------------------
// KfDeleteGroupsResponse
// -----------------------------------

#[derive(Encode, Decode, Serialize, Deserialize, KfDefault, Debug)]
pub struct KfDeleteGroupsResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation,
    /// or zero if the request did not violate any quota.
    pub throttle_time_ms: i32,

    /// The deletion results
    pub results: Vec<DeletableGroupResult>,
}

#[derive(Encode, Decode, Serialize, Deserialize, KfDefault, Debug)]
pub struct DeletableGroupResult {
    /// The group id
    pub group_id: String,

    /// The deletion error, or 0 if the deletion succeeded.
    pub error_code: ErrorCode,
}

// -----------------------------------
// Implementation - KfDeleteGroupsRequest
// -----------------------------------

impl Request for KfDeleteGroupsRequest {
    const API_KEY: u16 = 42;

    const MIN_API_VERSION: i16 = 0;
    const MAX_API_VERSION: i16 = 1;
    const DEFAULT_API_VERSION: i16 = 1;

    type Response = KfDeleteGroupsResponse;
}
