#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
RELATIVE_PATH="$DIR"/../../target/debug

RUST_LOG=sc_core=trace,cluster_cache=debug,k8_client=error,tokio_reactor=error "$RELATIVE_PATH"/sc-k8
