[tasks.robot-assistant-topic]
script = 'fluvio topic create robot-assistant'

[tasks.robot-assistant-server]
script = 'cargo run --bin robot-assistant-server'

[tasks.robot-assistant-wasm]
script = 'wasm-pack build examples/robot-assistant/wasm --target web --out-dir ../pkg'

[tasks.robot-assistant-build]
run_task = { name = [
    "robot-assistant-server",
    "robot-assistant-wasm"
], parallel = true }
