
test: test-function test-async-cb test-cb test-wrapper test-promise

test-function:
	cd example-function;make test

test-async-cb:
	cd example-async-cb;make test

test-cb:
	cd example-cb;make test

test-promise:
	cd example-promise;make test

test-wrapper:
	cd example-wrapper;make test	