
test: test-function test-cb test-class test-promise

test-function:
	cd function;make test

test-async-cb:
	cd async-cb;make test

test-cb:
	cd cb;make test

test-promise:
	cd promise;make test

test-class:
	cd class;make test	